### ISSUE TITLE
Dhrystone Spike 

### ISSUE THREAD

**Issue by lfernand4** [riscv/riscv-tests#116]
I am trying to run dhrystone with spike (rv64gc). /benchmark/make run.  
dhrystone.riscv.out : 
![image](https://user-images.githubusercontent.com/36438648/36543462-1ded1900-17e4-11e8-945b-d117146b8d7a.png)

 I think my results are wrong. It is correct ? and how to convert in Dhrystones/MHz ?

**Comment by Prince-Joy** [comment]
Hi,
Can you please help me about running dhrystone using spike? 
It would be great if you suggest me gnu-toolchain flags and necessary modifications if needed.
Thanks in advance

**Comment by aothman96** [comment]
how can I run Dhrystone on rocket-chip using spike??
