### ISSUE TITLE
sltu/sltiu seems to be missing from isa/rv32ui directory

### ISSUE THREAD

**Issue by rbarzic** [riscv/riscv-tests#12]
Those instructions are listed in the Risc-V spec 2.0 as part of the RV32I Base Instruction Set but I can't find them in riscv-tests

**Comment by vanjoe** [comment]
This is weird. This seems like an oversight. Do you want to submit a pull request?

**Comment by rbarzic** [comment]
I'll look at it but that may not happen very soon

**Comment by brettcannon** [comment]
[`slti`](https://github.com/riscv/riscv-tests/blob/master/isa/rv32ui/slti.S) seems to be there but `sltiu` is missing (although [rv64ui seems to have tests](https://github.com/riscv/riscv-tests/blob/master/isa/rv64ui/sltiu.S)).

**Comment by aswaterman** [comment]
fixed, thanks y'all
