### ISSUE TITLE
debug: propagate GDB command timeout more places?

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-tests#122]
I'm not sure how the GDB command timeout is passed through. For example, the `info threads` command can do quite a bit and take quite a long time on a slow (e.g. simulation), multi-core target:

https://github.com/riscv/riscv-tests/blob/45380af7d42ee3302fc229030694f8ea4506d79f/debug/testlib.py#L562

Is the target-specified timeout passed through at all in this case? If not, can we pass it through *every* time we call `gdb.command(...)`?

**Comment by timsifive** [comment]
timeout_sec is just something we tell gdb for its internal timeout. It's the maximum time gdb waits to hear back from the gdbserver (openocd in our case) before erroring out.

There's a separate timeout imposed by our test code, which is not configurable. It doesn't make sense for that timeout to be less than what we tell gdb, though, so I'll make a change to use the same configurable value for that timeout.

**Comment by timsifive** [comment]
Do you have a log or some detail on which timeout you ran into? I want to make sure I cover that code path.

**Comment by mwachs5** [comment]
#123 seems to do a good job here. Thanks! May need to tweak in the future but overall approach seems good.
