### ISSUE TITLE
rv64ua/lrsc.S reads from un-initialized memory.

### ISSUE THREAD

**Issue by ccelio** [riscv/riscv-tests#134]
**Background:**

The `lrsc` test performs a `load-reserve` from un-initialized memory. The write back value is `dontCare`, however, this can be problematic for co-simulation.

https://github.com/riscv/riscv-tests/blob/835f252ebe59ef782e96f467462a03754ea87936/isa/rv64ua/lrsc.S#L34-L41

It loads the address of `foo`, but then adds 1024 to it, in the hopes that 1024 is beyond the reach of the reservation (a painfully implementation-dependent value).

--------
**Question:**

Is leaving `foo+1024` un-initialized an oversight, or a deliberate choice? Is it wanting a smaller static binary to hasten loading?

**Comment by aswaterman** [comment]
The latter, but expanding the data section seems OK.

This test obviously needs to be rewritten at some point.

**Comment by ccelio** [comment]
Alright, I'm taking this on now. Question:

How do I provide some fixed spacing between two labels (e.g., between `foo` and `foo2`?) Is that `.align x`? That seems to enforce alignment, but doesn't work for the case where foo+4 hits the desired alignment. Also, what is x? `Size` or `log(size)`?

**Comment by ccelio** [comment]
FYI, the change in test time is not noticeable (the whole thing takes 9.7 seconds for my setup, +/- 0.3 s).

**Comment by aswaterman** [comment]
```.skip 1024```
