### ISSUE TITLE
How to run the benchmarks using proxy kernel in Rocket Chip emulator or FPGA frontend server?

### ISSUE THREAD

**Issue by asmitde** [riscv/riscv-tests#144]
Hello,

How do I run the compiled benchmarks through the proxy kernel on the RocketChip emulator?
Eg, I tried running the qsort.riscv in the emulator and it gives me the following error:
![image](https://user-images.githubusercontent.com/23269916/40755038-8676c2e8-644a-11e8-8ec2-02d2a9c1729d.png)

I get the same issue when running on the FPGA:
![image](https://user-images.githubusercontent.com/23269916/40755100-d39ba6b0-644a-11e8-807c-7e3ae7bf04a1.png)

The same program when run on spike without the proxy kernel, works fine.
![image](https://user-images.githubusercontent.com/23269916/40755462-9416504c-644c-11e8-89a6-9dfc2d83ed79.png)

What can be the issue?

**Comment by aswaterman** [comment]
Don't use the proxy kernel.  You should be able to run the tests directly on the RTL simulator or the Zynq frontend server, without pk.

**Comment by asmitde** [comment]
Thanks a lot! It worked without the pk.

I have a couple of questions, though.
1) What is the difference between mcycle and minstret?
2) When should we be using pk to run the riscv-elf binaries and when not? (Any programs I compiled manually with the riscv-gnu-toolchain needed pk to run, whereas the benchmarks don't need it, so I'm a bit confused how that works.)

Thanks for your help.

**Comment by muhammadali201** [comment]
@asmitde 

Did you get answers to your questions?

**Comment by colinschmidt** [comment]
`mcycle` is the number of cycles
`minstret` is the number of instructions
These can differ because of cache misses, branch mispredicts, pipeline flushes, etc.

The benchmarks have a bare-metal library/runtime that lets them run without pk.

Normal programs will need pk, or more (i.e. linux), depending on how much of a system them expect. pk doesn't implement a full kernel.

**Comment by AbhijittDhavlle** [comment]
How do you compile a C program for running on the fesvr-zynq or the RISCV Linux on rocket chip? I compiled initially with riscv62-unknown-elf-gcc and it executes with "spike pk hello". But the same compiled binary does not execute on the fesvr(with or without pk). How do I ensure that the compiled binary is RISCV compatible? Thanks ! Please reply asap!
