### ISSUE TITLE
question about load data when run spike 

### ISSUE THREAD

**Issue by IC-Dream** [riscv/riscv-tests#162]
Hi,

There is a self-checking directed test case in ~/riscv_tests/isa/rv32ui/lb.S to verify the load instruction. 

For example:
Assembly:
![assembly](https://user-images.githubusercontent.com/39543344/45415545-7b10d480-b6b0-11e8-8333-a8dd786035cb.PNG)

Disassembly:
![disassembly](https://user-images.githubusercontent.com/39543344/45415797-025e4800-b6b1-11e8-9720-6c44a4fb312b.PNG)

Commit log
![commit log](https://user-images.githubusercontent.com/39543344/45415785-f3779580-b6b0-11e8-86b1-1f8a45981bd0.PNG)

The load would load data back correctly and wrote to x30 correctly, but i don't know how the spike know the load data=32'hffff_ffff of the address=32'h80002000 ? Does the lb.S initialize this address to 32'hffff_ffff ? or something else ?

I am struggling to this, any help would be appreciated. 

Thanks
Dream

**Comment by IC-Dream** [comment]
More info: we didn't do any write to this address before the load.

**Comment by IC-Dream** [comment]
@jerralph here are the related code, but why the data of 0x80002001 ~ 0x80002003 are not 0x00/0xf0/0x0f respectively? 
Assembly:
![assembly data](https://user-images.githubusercontent.com/39543344/45462130-1cdc0400-b739-11e8-9e22-a7bba22afac5.PNG)
Disassembly:
![disassembly data](https://user-images.githubusercontent.com/39543344/45462140-26fe0280-b739-11e8-8285-d9d7c67ae7d8.PNG)

Thanks

**Comment by aswaterman** [comment]
`lb` loads only the byte at `80002000`, then sign-extends it to the register width.  So the bytes `80002001`-`80002003` do not matter.

**Comment by IC-Dream** [comment]
but the test 3/4/5 need to load data from the address 0x80002001-0x80002003, right ?
![load data](https://user-images.githubusercontent.com/39543344/45462444-624d0100-b73a-11e8-991f-e1620b0c8e77.PNG)

Thanks

**Comment by aswaterman** [comment]
Yeah.  Test 3 loads the byte at 80002001 (which has value 00), then sign-extends the byte, giving the result 00000000.

Test 4 loads the byte at 80002002 (which has value f0), then sign-extends the byte, giving the result fffffff0.

etc.

**Comment by aswaterman** [comment]
Is your question about the disassembly?  The disassembler is trying to treat these bytes as instructions, which of course makes no sense.  If you disassemble with different arguments (say, -d instead of -D), maybe you'll see the bytes as you expect.

**Comment by aswaterman** [comment]
I see. It’s not a riscv-tests question anymore, then. You can try other objdump flags, or use xxd or something.
