### ISSUE TITLE
misaligned jalr, value of rd

### ISSUE THREAD

**Issue by Imperas** [riscv/riscv-tests#166]
Hi All
in the testcode for ma_fetch.S
https://github.com/riscv/riscv-tests/blob/master/isa/rv64si/ma_fetch.S

If run in non RVC mode, the following comment describes the expected value after an exception due to a misaligned target address for JALR

> # verify that return address was not written
> bnez t1, fail

So it seems the test is expecting that the rd register must remain unchanged if the target address is misaligned (2 byte address) and RVC is disabled (eg RV32IM)

I have searched the 2.2 user and 1.10 priv spec to find where this is described, but cannot find this.
It seems logical, but could somebody please point me to a reference in the documentation that describes this behavior in the case where a misaligned exception occurs ?

Thx
Lee

**Comment by aswaterman** [comment]
It follows from the definition of a precise exception: the instruction either successfully executes or doesn’t alter any architectural state. The reason we don’t explicitly write that for JALR is that writing it would imply that JALR is a special case.

**Comment by eroom1966** [comment]
thanks for the update, this makes sense.

**Comment by Imperas** [comment]
Understood, and closing issue
thx
