### ISSUE TITLE
Can't run env/pt

### ISSUE THREAD

**Issue by LoveZJT** [riscv/riscv-tests#180]
I want to handle timer interrupt, so I add pt_tests in[ isa/Makefile](https://github.com/riscv/riscv-tests/blob/master/isa/Makefile):
```
$$($(1)_pt_tests): $(1)-pt-%: $(1)/%.S

	$$(RISCV_GCC) $(2) $$(RISCV_GCC_OPTS) -I$(src_dir)/../env/pt -I$(src_dir)/macros/scalar -T$(src_dir)/../env/pt/link.ld $$< -o $$@

$(1)_tests += $$($(1)_pt_tests)
```
But when I compile, there are some errors:
```
riscv-tests/isa/rv64mi/access.S:14: Error: Instruction csrr requires absolute expression
riscv-tests/isa/rv64mi/access.S:14: Error: Instruction csrw requires absolute expression
```
I think it failed while compiling `EXTRA_INIT_TIMER` in [env/pt/riscv_test.h](https://github.com/riscv/riscv-test-env/blob/6f31769d091bbd2ef504308633fbe8a870641894/pt/riscv_test.h). So, why `csrr a0, mtime` and `csrw mtimecmp, a0` failed?
Then I read [riscv-priviledge-v1.10](https://github.com/riscv/riscv-isa-manual/blob/master/release/riscv-privileged-v1.10.pdf), and I found that mtime and mtimecmp have been exposed as memory-mapped registers. And the manual provide the following code sequences to set mtimecmp:
```
# New comparand is in a1:a0.
li t0, -1
sw t0, mtimecmp # No smaller than old value.
sw a1, mtimecmp+4 # No smaller than new value.
sw a0, mtimecmp # New value.
```
However, while compiling `sw t0, mtimecmp`, there is another error: `illegal operand 'sw t0, mtimecmp'`
Now I feel confused. How can I generate timer interrupt? Have I got this completely wrong ?
Thx

**Comment by aswaterman** [comment]
It appears the `pt` code has bit-rotted.  You've got it mostly right, but the problem is that the spec is using pseudocode that isn't valid assembly.  First you need to load the address of mtimecmp into a register (say t1), then do `sw t0, 0(t1)` etc.

The address of mtimecmp depends on the platform.  It's not going to be defined as a link-time symbol, unless you write a special linker script.

**Comment by LoveZJT** [comment]
Thx
