### ISSUE TITLE
How to use these benchmarks?

### ISSUE THREAD

**Issue by JunnanLi** [riscv/riscv-tests#197]
Hi,
@pentin-as ,
@aswaterman 

After runing the command "make install", it generates x.riscv and x.riscv.dump. Does these can be run directly on riscv simulator, or I need to compile each banchmark using riscv64-unkonw-elf-gcc compiler?

**Comment by aswaterman** [comment]
x.riscv is a binary that can be run directly on Spike.

**Comment by JunnanLi** [comment]
@aswaterman , thanks.

**Comment by aswaterman** [comment]
you're welcome!
