### ISSUE TITLE
Support RV32E

### ISSUE THREAD

**Issue by colin4124** [riscv/riscv-tests#198]
https://github.com/riscv/riscv-tests/pull/196 It just supports the debug target. But the tests itself `test_macros.h` does not. https://github.com/riscv/riscv-tests/blob/master/isa/macros/scalar/test_macros.h

Does it support RISCV Test for RV32E in few month?

**Comment by aswaterman** [comment]
I don’t know if anyone is working on that, so you might consider
contributing it if you need it.
