### ISSUE TITLE
the pmp benchmark

### ISSUE THREAD

**Issue by Yi1101** [riscv/riscv-tests#232]
When I successfully compiled the pmp benchmark, and it produced the pmp.riscv file. However, when run the followed command, nothing print on the screen. For the pmp benchmark, there is no need to print something ?
>./spike  /riscv-gnu-toolchain/target/share/riscv-tests/benchmarks/pmp.riscv

**Comment by aswaterman** [comment]
Yeah, it doesn't print anything because it's really just a test program, not a benchmark.  It's in the benchmarks directory because that's where the build system for C programs lives.

**Comment by allenjbaum** [comment]
Can this issue be closed, please?

**Comment by Yi1101** [comment]
> Can this issue be closed, please?

sure
