### ISSUE TITLE
rv32mi-scall test never reaches its 'pass' or 'fail' labels

### ISSUE THREAD

**Issue by WRansohoff** [riscv/riscv-tests#270]
Similar to: https://github.com/riscv/riscv-tests/issues/256

I get the same "successful" trace, but my test harness does not mark it as a success because the 'pass' label is never reached and `a7` is never set to 93.

It looks like the test expects the `ecall` trap to call through to `mtvec_handler` where it can check that the `mcause` CSR holds the right value. But the right value is either `CAUSE_USER_MCALL` (8) or `CAUSE_MACHINE_MCALL` (11), and either one of those causes the program to jump to the infinite loop in `write_tohost`. Here's the relevant disassembly that I get:

```
00000004 <trap_vector>:
   4:	34202f73          	csrr	t5,mcause
   8:	00800f93          	li	t6,8
   c:	03ff0a63          	beq	t5,t6,40 <write_tohost>
  10:	00900f93          	li	t6,9
  14:	03ff0663          	beq	t5,t6,40 <write_tohost>
  18:	00b00f93          	li	t6,11
  1c:	03ff0263          	beq	t5,t6,40 <write_tohost>
  20:	00000f17          	auipc	t5,0x0
  24:	1f4f0f13          	addi	t5,t5,500 # 214 <mtvec_handler>
  28:	000f0463          	beqz	t5,30 <trap_vector+0x2c>
  2c:	000f0067          	jr	t5
  30:	34202f73          	csrr	t5,mcause
  34:	000f5463          	bgez	t5,3c <handle_exception>
  38:	0040006f          	j	3c <handle_exception>

0000003c <handle_exception>:
  3c:	5391e193          	ori	gp,gp,1337

00000040 <write_tohost>:
  40:	20000f17          	auipc	t5,0x20000
  44:	fc3f2023          	sw	gp,-64(t5) # 20000000 <_edata>
  48:	ff9ff06f          	j	40 <write_tohost>

[...reset vector, test code, etc...]

000001e4 <fail>:
 1e4:	0ff0000f          	fence
 1e8:	00018063          	beqz	gp,1e8 <fail+0x4>
 1ec:	00119193          	slli	gp,gp,0x1
 1f0:	0011e193          	ori	gp,gp,1
 1f4:	05d00893          	li	a7,93
 1f8:	00018513          	mv	a0,gp
 1fc:	00000073          	ecall

00000200 <pass>:
 200:	0ff0000f          	fence
 204:	00100193          	li	gp,1
 208:	05d00893          	li	a7,93
 20c:	00000513          	li	a0,0
 210:	00000073          	ecall

00000218 <mtvec_handler>:
 218:	342022f3          	csrr	t0,mcause
 21c:	fc6294e3          	bne	t0,t1,1e4 <fail>
 220:	00000397          	auipc	t2,0x0
 224:	fb838393          	addi	t2,t2,-72 # 1d8 <do_scall>
 228:	341022f3          	csrr	t0,mepc
 22c:	fa729ce3          	bne	t0,t2,1e4 <fail>
 230:	fd1ff06f          	j	200 <pass>
 234:	c0001073          	unimp
```

Sorry if this is caused by my build environment or something like that, but it looks like the `trap_vector` code is hardcoded in `riscv_test.h`.

**Comment by aswaterman** [comment]
You shouldn't be looking for hitting the `pass` label; you should be looking for something executing the RVTEST_PASS macro.  The RVTEST_PASS macro can be invoked in multiple places, with the `pass` label being one of them.

**Comment by WRansohoff** [comment]
Oh, thank you. Does the RVTEST_PASS macro get invoked by this test, though?

Sorry if I'm misreading how it is used - sometimes it's hard to predict how the C preprocessor will behave - but I don't see its contents in the #256 trace, and I don't see it used outside of `riscv_test.h`, `test_macros.h`, `rv64ui/simple.S`, `rv64ud/structural.S`, and some of the `rv64si` tests.

**Comment by aswaterman** [comment]
Some tests invoke RVTEST_PASS directly (as this one appears to do, under the `finish` label).  Others jump to the `pass` label, which itself invokes RVTEST_PASS.

**Comment by WRansohoff** [comment]
I could be missing something, but I don't see a `finish` label in the assembly file or the compiled code; this is `isa/rv64mi/scall.S`, which points to `isa/rv64si/scall.S` - not `isa/rv64si/csr.S`.

**Comment by aswaterman** [comment]
I was looking at the wrong test.  Give me a sec.

**Comment by aswaterman** [comment]
Yeah, the problem is that the default RVTEST_PASS macro uses `ecall`, so the trap handler can't distinguish RVTEST_PASS from the `ecall` instruction used in this test.  Thus, this test breaks the mold.

My recommendation is to not run this test in your environment.

**Comment by WRansohoff** [comment]
Makes sense; thank you for confirming that.
