### ISSUE TITLE
Error while building - Multiple definitions of `tohost` and `fromhost`

### ISSUE THREAD

**Issue by pcotret** [riscv/riscv-tests#286]
- Installed the newlib cross-compiler: https://github.com/riscv/riscv-gnu-toolchain
- Added the compiler to my PATH
- `export RISCV=<toolchain-directory>`
I got an error while compiling `riscv-tests`:
```bash
/opt/riscv/lib/gcc/riscv64-unknown-elf/10.1.0/../../../../riscv64-unknown-elf/bin/ld: /tmp/ccJxHjmW.o: in function `tohost':
(.tohost+0x0): multiple definition of `tohost'; /tmp/ccZrk0sX.o:(.sbss+0x10): first defined here
/opt/riscv/lib/gcc/riscv64-unknown-elf/10.1.0/../../../../riscv64-unknown-elf/bin/ld: /tmp/ccJxHjmW.o: in function `fromhost':
(.tohost+0x40): multiple definition of `fromhost'; /tmp/ccZrk0sX.o:(.sbss+0x8): first defined here
collect2: error: ld returned 1 exit status
```
The solution provided in #282 isn't satisfying for me as I would like to use my own compiler instead of downloading binaries from a third-party.

Any idea?

**Comment by aswaterman** [comment]
Recent versions of GCC default to `-fno-common`, causing these multiple-definition errors.  I didn't see them because I'm still using an older version of GCC.  This is now fixed on master.

**Comment by pcotret** [comment]
Thanks @aswaterman !

**Comment by zhutang** [comment]
> * Installed the newlib cross-compiler: https://github.com/riscv/riscv-gnu-toolchain
> * Added the compiler to my PATH
> * `export RISCV=<toolchain-directory>`
>   I got an error while compiling `riscv-tests`:
> 
> ```shell
> /opt/riscv/lib/gcc/riscv64-unknown-elf/10.1.0/../../../../riscv64-unknown-elf/bin/ld: /tmp/ccJxHjmW.o: in function `tohost':
> (.tohost+0x0): multiple definition of `tohost'; /tmp/ccZrk0sX.o:(.sbss+0x10): first defined here
> /opt/riscv/lib/gcc/riscv64-unknown-elf/10.1.0/../../../../riscv64-unknown-elf/bin/ld: /tmp/ccJxHjmW.o: in function `fromhost':
> (.tohost+0x40): multiple definition of `fromhost'; /tmp/ccZrk0sX.o:(.sbss+0x8): first defined here
> collect2: error: ld returned 1 exit status
> ```
> 
> The solution provided in #282 isn't satisfying for me as I would like to use my own compiler instead of downloading binaries from a third-party.
> 
> Any idea?

Excuse me, did you use your own compiler to fix this bug. I just git the master code of riscv-gnu-toolchain and compile them, and I want to test them for the opcodes-custom. however, i got this bug too.

**Comment by MstMoonshine** [comment]
> Recent versions of GCC default to `-fno-common`, causing these multiple-definition errors. I didn't see them because I'm still using an older version of GCC. This is now fixed on master.

Thanks, man. I solved this by adding `-fcommon` flag to Makefile under ./isa directory, following your hint.
