### ISSUE TITLE
Index of CSR misa in tests is wrong 

### ISSUE THREAD

**Issue by alexmechanic** [riscv/riscv-tests#32]
Watching dump for _rv32mi-p-mcsr_, instruction _800000c8 <test_2>_:
`800000c8:  30102573            csrr    a0,misa`
Bytecode for `csr` is supposed to be `misa`, but it equals **0b001100000001 = 0x301**
`misa` offest for v1.9 is **0xF10**, 0x301 does not exist in v1.9, for v1.7, 0x301 is offset for `mtvec` csr.

Are tests or compiler outdated?

**Comment by alexmechanic** [comment]
Just checked riscv-opcodes repo.
What do I need to follow, offests of csrs in riscv-opcodes or offsets from RISC-V ISA manual v1.9?

**Comment by mwachs5** [comment]
This is using 1.9.1 values. $misa is CSR 0x301.
