### ISSUE TITLE
napot.S sets U bit in non-leaf PTEs

### ISSUE THREAD

**Issue by pdonahue-ventana** [riscv/riscv-tests#352]
The privileged spec says:
> For non-leaf PTEs, the D, A, and U bits are reserved for future standard use and must be cleared by software for forward compatibility.

Step 2 of the translation algorithm says:
> Let pte be the value of the PTE at address a+va.vpn[i]×PTESIZE. (For Sv32, PTESIZE=4.) If accessing pte violates a PMA or PMP check, or if any reserved bits in pte are set, raise an access-fault exception corresponding to the original access type.

I don't see anything in Svnapot that changes that.

These lines in napot.S set the U bit in non-leaf PTEs:
https://github.com/riscv/riscv-tests/blob/master/isa/rv64si/napot.S#L61
https://github.com/riscv/riscv-tests/blob/master/isa/rv64si/napot.S#L81

Therefore, the instructions that attempt to use the NAPOT translation should be getting page faults.  This seems like a test bug and probably also a spike bug.

@daniellustig

**Comment by daniellustig** [comment]
Good catch, thank you @pdonahue-ventana.  I can fix this in #351 since I already have that PR open.

I also agree about this being a spike bug, at least wrt Priv 1.12 where we make it more explicit that setting reserved bits should trigger a page fault.  I will work on a fix for that as well.
