### ISSUE TITLE
Where is "riscv_test.h" located?

### ISSUE THREAD

**Issue by michael-etzkorn** [riscv/riscv-tests#359]
I'm trying to walk through the rv64ui-p-simple simulation and figured it be helpful to know what the test was executing to know what signals on the waveform to look at, but I'm having a hard time locating this file used in simple.S

**Comment by aswaterman** [comment]
`env/p/riscv_test.h`

`env` is a submodule so it might've been harder to search.

**Comment by michael-etzkorn** [comment]
Yeah `filename:riscv_test.h` doesn't pick it up. Thanks for the assist 👍
