### ISSUE TITLE
incorrect overflow test on isa/rv32um/div.S

### ISSUE THREAD

**Issue by eroom1966** [riscv/riscv-tests#61]
Hi

I thought I would mention that there may be a mistake in this test.
when running the tests on 32 / 64 bit, I only see an overflow issue on the 64 bit test, not the 32bit test
I think there is an error here 

  TEST_RR_OP( 6, div, -1<<63, -1<<63,  1 );
  TEST_RR_OP( 7, div, -1<<63, -1<<63, -1 );

I am guessing the shift should be 31, not 63 ?

E

**Comment by aswaterman** [comment]
Yes, it should be ```__riscv_xlen-1```; I'll fix it.  Thanks.

**Comment by aswaterman** [comment]
c26d7f39e6fabde07f16fd35d67a2414e674d488
