### ISSUE TITLE
Missing stuff for init.c

### ISSUE THREAD

**Issue by luismarques** [riscv/riscv-tests#77]
I've written a RISC-V simulator, and I wanted to run the available stress tests. I started here with riscv-tests. I ran ./configure with the latest SiFive SDK for macOS (the git master for RISC-V GCC fails to build from source in my macOS). It seemed to compile successfully. The repo readme doesn't have info on how to run the tests, so I started poking around and tried to `make debug-check`. That procedure involves compiling some C source files, including `programs/init.c`. That C source file includes `init.h`, which I can't find anywhere. Can you please provide more information on how to find the required dependencies?

**Comment by timsifive** [comment]
Sorry. I forgot to commit it.
