### ISSUE TITLE
Error: Instruction csrwi requires absolute expression

### ISSUE THREAD

**Issue by colin4124** [riscv/riscv-tests#9]
riscv-tests/isa/rv32mi/../rv64mi/ipi.S:30: Error: Instruction csrwi requires absolute expression
make[1]: *** [rv32mi-pm-ipi] error 1

**Comment by aswaterman** [comment]
That error message means that the assembler didn't understand which register the instruction refers to.  This probably means the version of riscv-tests you're using doesn't work with the version of the compiler you're using.  Did you check out the riscv-tools repo, which points to consistent versions of these sub-repos?

**Comment by colin4124** [comment]
Thx very much!
