### ISSUE TITLE
debug: "Timeout Exceeded" message in postMortemException

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-tests#98]
the gdbserver log file on a failure makes no sense to me. The error in this case was that I forgot to define `hart.ram`,  so the error that makes sense is 

```
    addrB = self.hart.ram + self.hart.ram_size - size
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
```

But I get this `Timeout exceeded.` message in the `postMortem Exception` log

This might just be user misunderstanding, but what is the point of `postMortem Exception` log? Why is a timeout reported when the error was pretty clear from the Python execution?

```
Test: MemTest64
Target: RocketSim
STARTING A SIMULATION
/scratch/megan/federation/rocket-chip/emulator/emulator-freechips.rocketchip.system-WithJtagDTMSystem_DefaultRV32Config-debug +verbose -v regression32.vcd dummybin | tee emulator.log
Waiting for OpenOCD to start...
--------------------------------[ Traceback ]---------------------------------
Traceback (most recent call last):
  File "/scratch/megan/federation/rocket-chip/riscv-tools/riscv-tests/debug/testlib.py", line 737, in run
    result = self.test()    # pylint: disable=no-member
  File "/scratch/megan/federation/rocket-chip/riscv-tools/riscv-tests/debug/gdbserver.py", line 156, in test
    self.access_test(8, 'long long')
  File "/scratch/megan/federation/rocket-chip/riscv-tools/riscv-tests/debug/gdbserver.py", line 136, in access_test
    addrB = self.hart.ram + self.hart.ram_size - size
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
---------------------------[ postMortem Exception ]---------------------------
Timeout exceeded.
...
```

**Comment by timsifive** [comment]
The point of the postMortem code is to gather some basic information about the target (eg. register contents) when a failure has occurred. Hopefully this saves you from having to do that by hand. In this case, a timeout was encountered while trying to gather this information. From what you posted above, you're seeing the thing that caused the test to fail as the main exception. I'm not sure how to make this more clear.
